### ISSUE TITLE
Validation of vatin-bundle

### ISSUE THREAD

**Issue by phpdeveloper1** [ddeboer/vatin-bundle#7] opened 2017-01-17 13:37 UTC
Using it as a service directly is working for me .But using annotation to validate the property of the model is not working.Any help would be appreciated.

**Comment by sstok** [comment] 2017-01-17 14:41
Can you explain what is not working exactly? Error, exception, not performing the validation, anything.

**Comment by phpdeveloper1** [comment] 2017-01-17 14:44
Not performing the validation.No errors or exception.

**Comment by sstok** [comment] 2017-01-17 14:58
Are other Constraints properly running? So if you have a NotBlank, leaving the value blank will give a violation.

**Comment by phpdeveloper1** [comment] 2017-01-17 15:08
Yes. Other constraints are running properly.Leaving the value blank is displaying the alert message.
This is how it is used in the model.
`/**
     * @ORM\Column(name="vat_number", type="string", nullable=true)
     * @Assert\NotNull(groups={"edit", "vat_number"},message="VAT Number is required")
     * @Assert\NotBlank(groups={"edit", "vat_number"},message="VAT Number is required")
     * @Vatin(checkExistence=true)
     */
    protected $vatNumber;`
OUTPUT:http://recordit.co/Xq0XFvNgAQ

**Comment by sstok** [comment] 2017-01-17 15:19
Hmm, `checkExistence` is set to true so it should work.

@ddeboer Can you confirm the Validator is still working with the latest Symfony version?

**Comment by phpdeveloper1** [comment] 2017-01-17 15:37
I am using symfony 2.8.16 version

**Comment by ddeboer** [comment] 2017-01-21 17:37
Ensured compatibility with newer Symfony versions on master. Can you try that and see if it resolves your problem?

**Comment by phpdeveloper1** [comment] 2017-01-22 23:55
Is it enough to  modifiy @stable in composer.json as "ddeboer/vatin-bundle" : "^1.0" ?

**Comment by ddeboer** [comment] 2017-01-23 07:00
You can (temporarily) switch to master like this:

```
"ddeboer/vatin-bundle": "dev-master"
```

**Comment by phpdeveloper1** [comment] 2017-01-23 22:07
Thanks for your message.I tried this solution as well.But still it didn't resolve my issue.

**Comment by ddeboer** [comment] 2017-01-25 11:28
Not sure what is wrong here. Added a passing functional test to ensure that the `@Vatin` validation annotation is working.

**Comment by phpdeveloper1** [comment] 2017-01-25 18:58
I am using symfony 2.8.16 version.But in ur composer.json it says 2.7 || 3.0 symfony framework.So is it not supporting 2.8 ?Could that be an issue?

**Comment by ddeboer** [comment] 2017-01-25 19:04
It says ^2.7, which includes 2.8. By the way, you can now update to version 2.0.0 of this bundle.

**Comment by ddeboer** [comment] 2017-01-26 09:53
We now also have a [test against Symfony 2.7](https://travis-ci.org/ddeboer/vatin-bundle/jobs/195475035), so I’m closing this issue as it seems to be unreproducible. While the most like cause is some issue in your Symfony app config, please feel free to open a PR with a failing test case if you can reproduce your problem.

**Closed by ddeboer** 2017-01-26 09:53 UTC
